tasks:
  - name: Installing Ionic 5 & Angular CLI
  - init: cd /workspace/MobDev_HDipComp/mobdev_ca3/
    command: cd /workspace/MobDev_HDipComp/mobdev_ca3/ && npm i -D -E @angular/cli && npx --yes ionic serve
